services:
  backend:
    build:
      context: ./backend
      dockerfile: ../build/backend.Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    container_name: backend
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=RajDiamondsDB
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    volumes:
      - ./backend:/app
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build:
      context: ./frontend
      dockerfile: ../build/frontend.Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: npm run dev

  db:
    container_name: db
    image: postgres
    environment:    
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: RajDiamondsDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
